import { Bean, Recipe } from './types';

export const MOCK_BEANS: Bean[] = [
  {
    id: '004',
    name: '브라질 다테하 버번컬렉션',
    roastery: '마이니치커피룸',
    country: '브라질',
    region: 'Cerrado Mineiro',
    farm: 'DATERRA',
    producer: '-',
    variety: 'Red Bourbon',
    altitude: '1150',
    process: 'Semi Washed',
    roastLevel: 'Medium Light',
    roastDate: '2025.6.16',
    price: 5250,
    imageUrl: '/images/id004.png',
    tastingRecords: [],
    tastingNotes: ['#헤이즐넛', '#땅콩', '#메이플', '#카라멜'],
    myNotes: ['#카라멜', '#단맛'],
    score: 87,
    memo: '데일리로 좋음. Ice보다는 Hot이 훨씬 단맛이 잘 올라옴',
    purchaseUrl: 'https://smartstore.naver.com/mynichecoffee'
  },
  {
    id: '003',
    name: '과테말라 라 에르모사 파나마 게샤 워시드',
    roastery: '센터커피',
    country: '과테말라',
    region: 'Chimaltenango',
    farm: 'La Hermosa',
    producer: 'Max Fernando Perez Rios',
    variety: 'Panama Gesha',
    altitude: '1800-2200',
    process: 'Fully Washed',
    roastLevel: 'Medium Light',
    roastDate: '2025.11.11',
    price: 14143,
    imageUrl: '/images/id003.png',
    tastingRecords: [],
    tastingNotes: ['#베르가못', '#만다린', '#실키'],
    myNotes: ['#크리미', '#오렌지'],
    score: 91,
    memo: '데일리로 좋음. 균형잡히고 식어서도 부정적인 맛 없는 긍정적인 맛',
    purchaseUrl: 'https://www.centercoffee.co.kr/67'
  },
  {
    id: '002',
    name: '에티오피아 벨레이네 바리소 내추럴',
    roastery: '향초',
    country: '에티오피',
    region: 'Sidama, Bensa',
    farm: 'Bombe',
    producer: 'Belayneh Bariso',
    variety: '74158, 74165',
    altitude: '2100-2380',
    process: 'Natural',
    roastLevel: 'Medium Light',
    roastDate: '2025.10.14',
    price: 11500,
    imageUrl: '/images/id002.png',
    tastingRecords: [],
    tastingNotes: ['#딸기', '#복숭아'],
    myNotes: ['#딸기'],
    score: 88,
    memo: '매우 화려함. 데일리보다는 가끔씩 먹으면 맛있음',
    purchaseUrl: 'https://smartstore.naver.com/hyangcho'
  },
  {
    id: '001',
    name: '콜롬비아 벨라 알레한드리아 게이샤 무산소 워시드',
    roastery: '토치커피',
    country: '콜롬비아',
    region: 'Huila, San Adolfo',
    farm: 'Bella Alejandria',
    producer: 'Wilder',
    variety: 'Gesha',
    altitude: '1800',
    process: 'Anaerobic Washed',
    roastLevel: 'Light',
    roastDate: '2025.11.04',
    price: 16000,
    imageUrl: '/images/id001.png',
    tastingRecords: [],
    tastingNotes: ['#레몬그라스', '#로즈마리', '#밀크티', '#망고', '#열대과일'],
    myNotes: ['#레몬그라스', '#흰꽃'],
    score: 90,
    memo: '무산소라 취향 타지만 직관적인 Yellow 계열의 맛을 느낄 수 있',
    purchaseUrl: 'https://smartstore.naver.com/toch'
  },
];

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'r006',
    title: '정인성 484 국룰 레시피',
    type: 'Hot/Iced',
    roastLevel: ['Medium', 'Dark'],
    dripper: 'Kalita',
    filter: '칼리타 전용 필터',
    grinder: '코만단테',
    grindSetting: '28클릭',
    waterTemp: 90,
    beanAmount: 20,
    waterAmount: 280,
    youtubeId: 'bVh1yP9imQk',
    youtubeStart: 0,
    steps: [
      { label: '뜸들이기', startTime: 0, endTime: 60, waterAmount: 40, addedAmount: 40 },
      { label: '1차 푸어', startTime: 60, endTime: 120, waterAmount: 120, addedAmount: 80 },
      { label: '2차 푸어', startTime: 120, endTime: 160, waterAmount: 160, addedAmount: 40 },
      { label: '120g 가수 또는 얼음', startTime: 160, endTime: 180, waterAmount: 280, addedAmount: 120 },
    ]
  },
  {
    id: 'r005',
    title: '테츠 카스야 4:6 레시피',
    type: 'Hot',
    roastLevel: ['Medium'],
    dripper: 'Hario V60',
    filter: '콘형 필터',
    grinder: '코만단테',
    grindSetting: '33클릭',
    waterTemp: 88,
    beanAmount: 20,
    waterAmount: 300,
    youtubeId: 'ewqza63GXh0',
    youtubeStart: 0,
    steps: [
      { label: '뜸들이기', startTime: 0, endTime: 45, waterAmount: 50, addedAmount: 50 },
      { label: '1차 푸어', startTime: 45, endTime: 90, waterAmount: 120, addedAmount: 70 },
      { label: '2차 푸어', startTime: 90, endTime: 135, waterAmount: 180, addedAmount: 60 },
      { label: '3차 푸어', startTime: 135, endTime: 165, waterAmount: 240, addedAmount: 60 },
      { label: '4차 푸어', startTime: 165, endTime: 210, waterAmount: 300, addedAmount: 60 },
    ]
  },
  {
    id: 'r004',
    title: '정인성 4664 국룰 레시피',
    type: 'Hot/Iced',
    roastLevel: ['Light', 'Medium'],
    dripper: '전부 가능',
    filter: '전부 가능',
    grinder: '코만단테',
    grindSetting: '26클릭',
    waterTemp: 93,
    beanAmount: 18,
    waterAmount: 270,
    youtubeId: 'i7Q-pvahrXw',
    youtubeStart: 85,
    steps: [
      { label: '뜸들이기', startTime: 0, endTime: 40, waterAmount: 40, addedAmount: 40 },
      { label: '안-바깥', startTime: 40, endTime: 70, waterAmount: 100, addedAmount: 60 },
      { label: '안-바깥', startTime: 70, endTime: 100, waterAmount: 160, addedAmount: 60 },
      { label: '안-바깥-센터푸어', startTime: 100, endTime: 160, waterAmount: 200, addedAmount: 40 },
      { label: '70g 가수 또는 얼음', startTime: 160, endTime: 190, waterAmount: 270, addedAmount: 70 },
    ]
  },
  {
    id: 'r003',
    title: '아이덴티티커피랩 오리가미 Ver2(핫)',
    type: 'Hot',
    roastLevel: ['Light', 'Medium'],
    dripper: 'Origami',
    filter: '카펙 TH-3 4컵',
    grinder: '코만단테',
    grindSetting: '22클릭',
    waterTemp: 92,
    beanAmount: 16,
    waterAmount: 260,
    youtubeId: 'k0YQ8vKRD4s',
    youtubeStart: 316,
    steps: [
      { label: '뜸들이기', startTime: 0, endTime: 35, waterAmount: 60, addedAmount: 60 },
      { label: '안-바깥', startTime: 35, endTime: 70, waterAmount: 140, addedAmount: 100 },
      { label: '바깥-안', startTime: 70, endTime: 85, waterAmount: 200, addedAmount: 60 },
      { label: '센터푸어', startTime: 85, endTime: 150, waterAmount: 260, addedAmount: 60 },
    ]
  },
  {
    id: 'r002',
    title: '아이덴티티커피랩 오리가미 Ver2(아이스)',
    type: 'Iced',
    roastLevel: ['Light', 'Medium'],
    dripper: 'Origami',
    filter: '카펙 TH-3 4컵',
    grinder: '코만단테',
    grindSetting: '20',
    waterTemp: 92,
    beanAmount: 19,
    waterAmount: 200,
    youtubeId: 'k0YQ8vKRD4s',
    youtubeStart: 771,
    steps: [
      { label: '가늘게 붓기', startTime: 0, endTime: 35, waterAmount: 40, addedAmount: 40 },
      { label: '안-바깥', startTime: 35, endTime: 70, waterAmount: 100, addedAmount: 60 },
      { label: '바깥-안', startTime: 70, endTime: 100, waterAmount: 150, addedAmount: 50 },
      { label: '바깥-안', startTime: 100, endTime: 130, waterAmount: 200, addedAmount: 50 },
    ]
  },
  {
    id: 'r001',
    title: '용챔 하리오',
    type: 'Hot',
    roastLevel: ['Light', 'Medium'],
    dripper: 'Hario V60',
    filter: '카펙 TH-3 4컵',
    grinder: '코만단테',
    grindSetting: '28 클릭',
    waterTemp: 93,
    beanAmount: 18,
    waterAmount: 260,
    youtubeId: 'hgxL-XugBvQ',
    steps: [
      { label: '뜸들이기', startTime: 0, endTime: 40, waterAmount: 40, addedAmount: 40 },
      { label: '중간 물줄기', startTime: 40, endTime: 70, waterAmount: 110, addedAmount: 70 },
      { label: '중간 물줄기', startTime: 70, endTime: 105, waterAmount: 210, addedAmount: 100 },
      { label: '안-바깥-센터푸어', startTime: 105, endTime: 140, waterAmount: 260, addedAmount: 50 },
    ]
  },
];
